In [1]:
import torch
import numpy as np

In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [3]:
x_data

tensor([[1, 2],
        [3, 4]])

In [4]:
data = np.array(data)
data

array([[1, 2],
       [3, 4]])

In [7]:
x_np = torch.from_numpy(data)

In [8]:
x_np

tensor([[1, 2],
        [3, 4]])

In [11]:
x_ones = torch.ones_like(x_np)
x_ones

tensor([[1, 1],
        [1, 1]])

In [13]:
x_rand = torch.rand_like(x_np, dtype=torch.float)
x_rand

tensor([[0.7399, 0.7427],
        [0.5489, 0.5539]])

In [15]:
x_randint = torch.randint_like(x_np, low=1, high=100)
x_randint

tensor([[32, 66],
        [11, 93]])

In [63]:
shape = (3,2,3)

tens = torch.rand(shape)
tens

tensor([[[0.5557, 0.1003, 0.7896],
         [0.4180, 0.1262, 0.3411]],

        [[0.7526, 0.9894, 0.5266],
         [0.4877, 0.7098, 0.2970]],

        [[0.5149, 0.3712, 0.1112],
         [0.9475, 0.6278, 0.8893]]])

In [64]:
tens.dtype

torch.float32

In [65]:
tens.device

device(type='cpu')

In [72]:
tensor = torch.ones(4,4)
print(f'First row: {tensor[0]}')
print(f'First Col: {tensor[:,0]}')
print(f'Last Col: {tensor[...,-1]}')

First row: tensor([1., 1., 1., 1.])
First Col: tensor([1., 1., 1., 1.])
Last Col: tensor([1., 1., 1., 1.])


In [74]:
tensor[:,1] = 0
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [75]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
t1

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

In [79]:
t2 = torch.cat([tensor, tensor, tensor], dim=0)
t2

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [81]:
y1 = tensor @ tensor.T
y1

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [83]:
y2 = tensor.matmul(tensor.T)
y2

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [84]:
z1 = tensor * tensor
z1

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [85]:
z2 = tensor.mul(tensor)
z2

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [86]:
z3 = torch.rand_like(tensor)
z3

tensor([[0.3668, 0.0130, 0.0434, 0.4934],
        [0.3380, 0.4232, 0.5199, 0.5750],
        [0.8644, 0.5605, 0.0308, 0.0514],
        [0.8188, 0.7243, 0.3286, 0.1958]])

In [87]:
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [89]:
z3

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [90]:
agg = tensor.sum()
agg

tensor(12.)

In [91]:
agg.type

<function Tensor.type>

In [94]:
agg_item = agg.item()
agg_item, type(agg_item)

(12.0, float)

In [95]:
tensor.add_(5)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

In [96]:
tensor.add(tensor)

tensor([[12., 10., 12., 12.],
        [12., 10., 12., 12.],
        [12., 10., 12., 12.],
        [12., 10., 12., 12.]])