In [1]:
import torch
import numpy as np

In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [3]:
x_data

tensor([[1, 2],
        [3, 4]])

In [4]:
data = np.array(data)
data

array([[1, 2],
       [3, 4]])

In [5]:
x_np = torch.from_numpy(data)

In [6]:
x_np

tensor([[1, 2],
        [3, 4]])

In [7]:
x_ones = torch.ones_like(x_np)
x_ones

tensor([[1, 1],
        [1, 1]])

In [8]:
x_rand = torch.rand_like(x_np, dtype=torch.float)
x_rand

tensor([[0.9827, 0.0383],
        [0.8896, 0.4422]])

In [9]:
x_randint = torch.randint_like(x_np, low=1, high=100)
x_randint

tensor([[74, 84],
        [45, 10]])

In [10]:
shape = (3,2,3)

tens = torch.rand(shape)
tens

tensor([[[0.6356, 0.0649, 0.1083],
         [0.0360, 0.9621, 0.9782]],

        [[0.6962, 0.9104, 0.9072],
         [0.8067, 0.8409, 0.4390]],

        [[0.5169, 0.3220, 0.2843],
         [0.7129, 0.5625, 0.3456]]])

In [11]:
tens.dtype

torch.float32

In [12]:
tens.device

device(type='cpu')

In [13]:
tensor = torch.ones(4,4)
print(f'First row: {tensor[0]}')
print(f'First Col: {tensor[:,0]}')
print(f'Last Col: {tensor[...,-1]}')

First row: tensor([1., 1., 1., 1.])
First Col: tensor([1., 1., 1., 1.])
Last Col: tensor([1., 1., 1., 1.])


In [14]:
tensor[:,1] = 0
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [15]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
t1

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

In [16]:
t2 = torch.cat([tensor, tensor, tensor], dim=0)
t2

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [17]:
y1 = tensor @ tensor.T
y1

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [18]:
y2 = tensor.matmul(tensor.T)
y2

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [19]:
z1 = tensor * tensor
z1

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [20]:
z2 = tensor.mul(tensor)
z2

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [21]:
z3 = torch.rand_like(tensor)
z3

tensor([[0.1047, 0.1171, 0.5462, 0.6546],
        [0.2571, 0.1187, 0.8088, 0.6732],
        [0.8482, 0.9082, 0.2941, 0.8122],
        [0.6259, 0.6990, 0.2410, 0.5628]])

In [22]:
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [23]:
z3

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [24]:
agg = tensor.sum()
agg

tensor(12.)

In [25]:
agg.type

<function Tensor.type>

In [26]:
agg_item = agg.item()
agg_item, type(agg_item)

(12.0, float)

In [27]:
tensor.add_(5)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

In [28]:
tensor.add(tensor)

tensor([[12., 10., 12., 12.],
        [12., 10., 12., 12.],
        [12., 10., 12., 12.],
        [12., 10., 12., 12.]])